INFO     xM_Appium_UI_Test:send_appium.py:118 ----------------appium UI自动化测试开始----------------
INFO     xM_Appium_UI_Test:send_appium.py:119 用例的名称是：输入的内容和标题为空-新增笔记
INFO     xM_Appium_UI_Test:send_appium.py:120 用例的所属模块是：新增模块
INFO     xM_Appium_UI_Test:send_appium.py:121 用例的Data是：{'title': '标题_03', 'content': 'xx'}
INFO     xM_Appium_UI_Test:send_appium.py:175 用例的响应信息是：标题_03
INFO     xM_Appium_UI_Test:send_appium.py:176 用例的断言信息是：标题_02
INFO     xM_Appium_UI_Test:send_appium.py:204 断言失败：返回的结果 标题_03 中不包含：标题_02
ERROR    xM_Appium_UI_Test:send_appium.py:181 appium 自动化测试报错！
Traceback (most recent call last):
  File "D:\PythonPc_App\Appium\common\send_appium.py", line 178, in all_send_appium
    self.assert_result(self.test_yaml['validate'], Response_Text)  # 调用下面的方法处理
  File "D:\PythonPc_App\Appium\common\send_appium.py", line 197, in assert_result
    assert all_flag == 0  # True表示断言通过
AssertionError